/* tslint:disable */
/* eslint-disable */
/**
 * Content Creator and Scheduler API
 * Content Creator and Scheduler API for frontend
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentForTwitterPost } from './ContentForTwitterPost';
import {
    ContentForTwitterPostFromJSON,
    ContentForTwitterPostFromJSONTyped,
    ContentForTwitterPostToJSON,
} from './ContentForTwitterPost';

/**
 * 
 * @export
 * @interface ContentsList200Response
 */
export interface ContentsList200Response {
    /**
     * 
     * @type {number}
     * @memberof ContentsList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof ContentsList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentsList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<ContentForTwitterPost>}
     * @memberof ContentsList200Response
     */
    results: Array<ContentForTwitterPost>;
}

/**
 * Check if a given object implements the ContentsList200Response interface.
 */
export function instanceOfContentsList200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function ContentsList200ResponseFromJSON(json: any): ContentsList200Response {
    return ContentsList200ResponseFromJSONTyped(json, false);
}

export function ContentsList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentsList200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ContentForTwitterPostFromJSON)),
    };
}

export function ContentsList200ResponseToJSON(value?: ContentsList200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(ContentForTwitterPostToJSON)),
    };
}

