/* tslint:disable */
/* eslint-disable */
/**
 * Content Creator and Scheduler API
 * Content Creator and Scheduler API for frontend
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ImageForTwitterPost } from './ImageForTwitterPost';
import {
    ImageForTwitterPostFromJSON,
    ImageForTwitterPostFromJSONTyped,
    ImageForTwitterPostToJSON,
} from './ImageForTwitterPost';

/**
 * 
 * @export
 * @interface ImagesList200Response
 */
export interface ImagesList200Response {
    /**
     * 
     * @type {number}
     * @memberof ImagesList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof ImagesList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImagesList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<ImageForTwitterPost>}
     * @memberof ImagesList200Response
     */
    results: Array<ImageForTwitterPost>;
}

/**
 * Check if a given object implements the ImagesList200Response interface.
 */
export function instanceOfImagesList200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function ImagesList200ResponseFromJSON(json: any): ImagesList200Response {
    return ImagesList200ResponseFromJSONTyped(json, false);
}

export function ImagesList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImagesList200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ImageForTwitterPostFromJSON)),
    };
}

export function ImagesList200ResponseToJSON(value?: ImagesList200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(ImageForTwitterPostToJSON)),
    };
}

