/* tslint:disable */
/* eslint-disable */
/**
 * Content Creator and Scheduler API
 * Content Creator and Scheduler API for frontend
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Profile } from './Profile';
import {
    ProfileFromJSON,
    ProfileFromJSONTyped,
    ProfileToJSON,
} from './Profile';

/**
 * 
 * @export
 * @interface ProfilesList200Response
 */
export interface ProfilesList200Response {
    /**
     * 
     * @type {number}
     * @memberof ProfilesList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof ProfilesList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfilesList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Profile>}
     * @memberof ProfilesList200Response
     */
    results: Array<Profile>;
}

/**
 * Check if a given object implements the ProfilesList200Response interface.
 */
export function instanceOfProfilesList200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function ProfilesList200ResponseFromJSON(json: any): ProfilesList200Response {
    return ProfilesList200ResponseFromJSONTyped(json, false);
}

export function ProfilesList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilesList200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ProfileFromJSON)),
    };
}

export function ProfilesList200ResponseToJSON(value?: ProfilesList200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(ProfileToJSON)),
    };
}

