/* tslint:disable */
/* eslint-disable */
/**
 * Content Creator and Scheduler API
 * Content Creator and Scheduler API for frontend
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Project } from './Project';
import {
    ProjectFromJSON,
    ProjectFromJSONTyped,
    ProjectToJSON,
} from './Project';

/**
 * 
 * @export
 * @interface ProjectsList200Response
 */
export interface ProjectsList200Response {
    /**
     * 
     * @type {number}
     * @memberof ProjectsList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectsList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectsList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Project>}
     * @memberof ProjectsList200Response
     */
    results: Array<Project>;
}

/**
 * Check if a given object implements the ProjectsList200Response interface.
 */
export function instanceOfProjectsList200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function ProjectsList200ResponseFromJSON(json: any): ProjectsList200Response {
    return ProjectsList200ResponseFromJSONTyped(json, false);
}

export function ProjectsList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsList200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ProjectFromJSON)),
    };
}

export function ProjectsList200ResponseToJSON(value?: ProjectsList200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(ProjectToJSON)),
    };
}

