/* tslint:disable */
/* eslint-disable */
/**
 * Content Creator and Scheduler API
 * Content Creator and Scheduler API for frontend
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Timezone
 */
export interface Timezone {
    /**
     * 
     * @type {number}
     * @memberof Timezone
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof Timezone
     */
    name: string;
}

/**
 * Check if a given object implements the Timezone interface.
 */
export function instanceOfTimezone(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function TimezoneFromJSON(json: any): Timezone {
    return TimezoneFromJSONTyped(json, false);
}

export function TimezoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): Timezone {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
    };
}

export function TimezoneToJSON(value?: Timezone | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

