/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TwitterAccount } from './TwitterAccount';
import {
    TwitterAccountFromJSON,
    TwitterAccountFromJSONTyped,
    TwitterAccountToJSON,
} from './TwitterAccount';

/**
 * 
 * @export
 * @interface TwitterUsersList200Response
 */
export interface TwitterUsersList200Response {
    /**
     * 
     * @type {number}
     * @memberof TwitterUsersList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof TwitterUsersList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TwitterUsersList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<TwitterAccount>}
     * @memberof TwitterUsersList200Response
     */
    results: Array<TwitterAccount>;
}

/**
 * Check if a given object implements the TwitterUsersList200Response interface.
 */
export function instanceOfTwitterUsersList200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function TwitterUsersList200ResponseFromJSON(json: any): TwitterUsersList200Response {
    return TwitterUsersList200ResponseFromJSONTyped(json, false);
}

export function TwitterUsersList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TwitterUsersList200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(TwitterAccountFromJSON)),
    };
}

export function TwitterUsersList200ResponseToJSON(value?: TwitterUsersList200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(TwitterAccountToJSON)),
    };
}

