/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TwitterAccount
 */
export interface TwitterAccount {
    /**
     * 
     * @type {number}
     * @memberof TwitterAccount
     */
    readonly websiteUser?: number;
    /**
     * Screen name of Twitter user
     * @type {string}
     * @memberof TwitterAccount
     */
    username: string;
    /**
     * Display name(first and last name) of Twitter user
     * @type {string}
     * @memberof TwitterAccount
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TwitterAccount
     */
    userId: string;
}

/**
 * Check if a given object implements the TwitterAccount interface.
 */
export function instanceOfTwitterAccount(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function TwitterAccountFromJSON(json: any): TwitterAccount {
    return TwitterAccountFromJSONTyped(json, false);
}

export function TwitterAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): TwitterAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'websiteUser': !exists(json, 'website_user') ? undefined : json['website_user'],
        'username': json['username'],
        'name': json['name'],
        'userId': json['user_id'],
    };
}

export function TwitterAccountToJSON(value?: TwitterAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'name': value.name,
        'user_id': value.userId,
    };
}

