/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface UsersList200Response
 */
export interface UsersList200Response {
    /**
     * 
     * @type {number}
     * @memberof UsersList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof UsersList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UsersList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<User>}
     * @memberof UsersList200Response
     */
    results: Array<User>;
}

/**
 * Check if a given object implements the UsersList200Response interface.
 */
export function instanceOfUsersList200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function UsersList200ResponseFromJSON(json: any): UsersList200Response {
    return UsersList200ResponseFromJSONTyped(json, false);
}

export function UsersList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersList200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(UserFromJSON)),
    };
}

export function UsersList200ResponseToJSON(value?: UsersList200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(UserToJSON)),
    };
}

